/**
 * Comment Checker Hook
 * 
 * Checks files for AI-generated comments and provides feedback.
 * Detects patterns like "// Generated by", "// AI-", etc.
 */

import { log } from "../../shared/logger"

interface PluginInput {
  directory: string
}

interface PendingCall {
  filePath: string
  content?: string
  oldString?: string
  newString?: string
  edits?: Array<{ old_string: string; new_string: string }>
  tool: "write" | "edit" | "multiedit"
  sessionID: string
  timestamp: number
}

interface ToolExecuteInput {
  tool: string
  sessionID: string
  callID: string
}

interface ToolExecuteOutput {
  title: string
  output: string
  metadata: unknown
}

/**
 * AI comment patterns to detect.
 */
const AI_COMMENT_PATTERNS = [
  /\/\/\s*(generated|created|written|auto-generated)\s+(by|with|using)/i,
  /\/\/\s*ai[-\s]*(generated|assistant|code)/i,
  /\/\/\s*(this\s+(code|file|function)\s+was\s+generated)/i,
  /\/\*\*?\s*(generated|created|written)\s+(by|with|using)/i,
  /\/\/\s*claude[-\s]?(code|wrote|generated)/i,
  /\/\/\s*copilot[-\s]?(generated|suggestion)/i,
  /\/\/\s*auto[-\s]?generated/i,
]

/**
 * Check content for AI comments.
 */
function hasAIComments(content: string): { found: boolean; patterns: string[] } {
  const found: string[] = []
  
  for (const pattern of AI_COMMENT_PATTERNS) {
    if (pattern.test(content)) {
      found.push(pattern.source)
    }
  }

  return { found: found.length > 0, patterns: found }
}

/**
 * Create the comment checker hook.
 */
export function createCommentCheckerHooks(config?: { enabled?: boolean }) {
  const pendingCalls = new Map<string, PendingCall>()
  const enabled = config?.enabled ?? true

  /**
   * Handle tool execution before - register pending call.
   */
  const toolExecuteBefore = async (
    input: ToolExecuteInput,
    output: { args: Record<string, unknown> }
  ): Promise<void> => {
    if (!enabled) return

    const toolLower = input.tool.toLowerCase()
    if (toolLower !== "write" && toolLower !== "edit" && toolLower !== "multiedit") {
      return
    }

    const filePath = (output.args.filePath ?? output.args.file_path ?? output.args.path) as string | undefined
    const content = output.args.content as string | undefined
    const oldString = output.args.oldString ?? output.args.old_string as string | undefined
    const newString = output.args.newString ?? output.args.new_string as string | undefined
    const edits = output.args.edits as Array<{ old_string: string; new_string: string }> | undefined

    if (!filePath) return

    pendingCalls.set(input.callID, {
      filePath,
      content,
      oldString: oldString as string | undefined,
      newString: newString as string | undefined,
      edits,
      tool: toolLower as "write" | "edit" | "multiedit",
      sessionID: input.sessionID,
      timestamp: Date.now(),
    })
  }

  /**
   * Handle tool execution after - check for AI comments.
   */
  const toolExecuteAfter = async (
    input: ToolExecuteInput,
    output: ToolExecuteOutput
  ): Promise<void> => {
    if (!enabled) return

    const pending = pendingCalls.get(input.callID)
    if (!pending) return

    pendingCalls.delete(input.callID)

    // Skip if tool execution failed
    const outputLower = (output.output ?? "").toLowerCase()
    const isToolFailure =
      outputLower.includes("error:") ||
      outputLower.includes("failed to") ||
      outputLower.startsWith("error")

    if (isToolFailure) {
      return
    }

    // Check content based on tool type
    let contentToCheck: string | undefined

    if (pending.tool === "write" && pending.content) {
      contentToCheck = pending.content
    } else if ((pending.tool === "edit" || pending.tool === "multiedit") && pending.newString) {
      contentToCheck = pending.newString
    } else if (pending.edits) {
      // For multiedit, check all new strings
      contentToCheck = pending.edits.map(e => e.new_string).join("\n")
    }

    if (!contentToCheck) return

    const { found, patterns } = hasAIComments(contentToCheck)
    
    if (found) {
      log("[comment-checker] AI comment patterns detected", {
        sessionID: pending.sessionID,
        filePath: pending.filePath,
        patterns,
      })

      // Append warning to output
      output.output += "\n\n<comment-checker-warning>\n"
      output.output += "⚠️ **AI-generated comment patterns detected** in the file content.\n"
      output.output += "Consider removing these patterns for cleaner code:\n"
      output.output += `- ${patterns.join("\n- ")}\n`
      output.output += "</comment-checker-warning>\n"
    }
  }

  return {
    "tool.execute.before": toolExecuteBefore,
    "tool.execute.after": toolExecuteAfter,
  }
}